version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: threemegawatt_local_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start
